name: Check with Tox
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: Run tests with tox
    runs-on: ubuntu-latest
    steps:
      - name: Start pyright install
        run: sudo snap install --classic pyright --no-wait
      - name: Set up tempdir on a tmpfs
        run: |
          export TMPDIR="${RUNNER_TEMP}/tmp"
          mkdir -p $TMPDIR
          echo TMPDIR=$TMPDIR >> $GITHUB_ENV
          sudo mount -t tmpfs -o size=1024M,uid=$UID,gid=$(id -g),mode=700,inode64 none $TMPDIR
      - uses: actions/checkout@v3
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'
          python-version: |
            3.8
            3.9
            3.10
            3.11
            pypy3.9
      - name: Install Tox
        run: python -m pip install tox-gh tox
      - name: Setup test suite
        run: |
          tox run-parallel --workdir $TMPDIR --parallel-no-spinner -vv --notest
      - name: Run test suite
        run: tox run-parallel --skip-pkg-install --parallel-no-spinner -vv
        env:
          PYTEST_ADDOPTS: "--durations=10"
      - if: ${{ always() }}
        name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ env.TMPDIR }}/tox-pyxdg2/log/**/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          output: both
      - if: ${{ always() }}
        run: mv code-coverage-results.md ${TMPDIR}/log
      - name: Lint with tox
        if: ${{ always() }}
        run: |
          snap watch '--last=install?'  # Ensure pyright install has completed.
          tox run -vv -m ci-static
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: ${{ env.TMPDIR }}/tox-pyxdg2/log

