name: Check with Tox
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: Run tests with tox
    runs-on: ubuntu-latest
    steps:
      - name: Setup python versions
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            pypy3.9
      - uses: actions/checkout@v3
      - name: Install tox-gh
        run: python -m pip install tox-gh tox
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
